// src/components/buhodev/PasswordGenerator.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import { fly } from 'svelte/transition'
	import { backOut } from 'svelte/easing'
	import { generate_password, type DefaultOptions } from './generate_password'
	import { copy_to_clipboard } from './copy_to_clipboard'
	import UltraGradientBackground from './UltraGradientBackground.svelte'

	let password = ""
	let isCopied = false
	let animate = true
	let length = 6

	const DEFAULT_OPTIONS: DefaultOptions = {
		uppercase: true,
		lowercase: true,
		numbers: true,
		symbols: false
	}

	function handleSuccessfulCopy() {
		isCopied = true
		setTimeout(() => (isCopied = false), 1000)
	}

	onMount(() => password = generate_password(length, DEFAULT_OPTIONS))
</script>

<UltraGradientBackground />

<div
	class="absolute border-gray-600/20 border-2 p-6 bg-gray-800/20 backdrop-blur-sm top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-white rounded-lg"
>
	<!-- Title -->
	<h1 class="text-5xl font-bold text-center">Password Generator</h1>

	<!-- Password -->
	<div class="flex items-center justify-center mt-8 w-full">
		<span class="flex font-bold text-3xl mr-auto">
			{#if !animate}
				{password}
			{:else}
				{#key password}
					{#each password.split('') as char, i}
						{#if !isNaN(Number(char))}
							<span
								class="block text-pink-400"
								in:fly={{
									y: -5,
									delay: 15 * i,
									easing: backOut
								}}
							>
								{char}
							</span>
						{:else if /[^a-zA-Z]/.test(char)}
							<span
								class="block text-blue-400"
								in:fly={{
									y: -5,
									delay: 15 * i,
									easing: backOut
								}}
							>
								{char}
							</span>
						{:else}
							<span
								class="block"
								in:fly={{
									y: -5,
									delay: 15 * i,
									easing: backOut
								}}
							>
								{char}
							</span>
						{/if}
					{/each}
				{/key}
			{/if}
		</span>

		<button
			use:copy_to_clipboard={{ text: password }}
			on:copied={handleSuccessfulCopy}
			on:error={() => alert('error')}
			title="Copy password"
			class="rounded-md border-2 border-slate-700 hover:border-slate-600 flex items-center justify-center py-1 px-2"
		>
			{#if !isCopied}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					class="w-6 h-6"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z"
					/>
				</svg>
			{:else}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					class="w-6 h-6"
				>
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m8.9-4.414c.376.023.75.05 1.124.08 1.131.094 1.976 1.057 1.976 2.192V16.5A2.25 2.25 0 0118 18.75h-2.25m-7.5-10.5H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V18.75m-7.5-10.5h6.375c.621 0 1.125.504 1.125 1.125v9.375m-8.25-3l1.5 1.5 3-3.75"
					/>
				</svg>
			{/if}
		</button>

		<button
			on:click={() => (password = generate_password(length, DEFAULT_OPTIONS))}
			title="Refresh password"
			class="rounded-md border-2 border-slate-700 hover:border-slate-600 group flex items-center justify-center py-1 px-2"
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
				stroke-width="1.5"
				stroke="currentColor"
				class="w-6 h-6 group-hover:-rotate-3 duration-75 transition-transform spin"
			>
				<path
					stroke-linecap="round"
					stroke-linejoin="round"
					d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99"
				/>
			</svg>
		</button>
	</div>

	<label for="length" class="mt-8 inline-block w-full">
		<span class="text-lg">Length: {length}</span>
		<input type="range" min="4" max="30" class="w-full mt-2" bind:value={length} />
	</label>

	<!-- Generate Password Button -->
	<button
		on:click={() => (password = generate_password(length, DEFAULT_OPTIONS))}
		class="relative inline-flex w-full h-12 mt-8 bg-gradient-to-tr from-blue-700 to-sky-400 cursor-pointer touch-manipulation select-none items-center justify-center whitespace-nowrap rounded-md border-0 px-4 text-lg leading-none text-white hover:-translate-y-[1px] active:translate-y-[1px]"
		>Generate Password</button
	>
</div>

<style>
	.group:active .spin {
		animation: spin 0.15s linear;
	}
	@keyframes spin {
		from {
			transform: rotate(0deg);
		}
		to {
			transform: rotate(180deg);
		}
	}
</style>

// src/components/danizt/PasswordGenerator.jsx
import React, { useState, useEffect } from 'react'
import { getRandomPassword, copyPassword } from './utils/handlePassword'
import CopySvg from './icons/copySvg'

const NUMBERS = '0123456789'
const LOWER_CASE = 'abcdefghijklmnopqrstuvwxyz'
const UPPER_CASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
const SPECIAL = '!#$%&()*+,-./:;<=>?@[]^_`{|}~'

const hover1Style =
	'relative inline-flex items-center justify-center p-0.5 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white dark:focus:ring-cyan-800'

const hover2Style =
	'relative transition-all ease-in duration-150 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0 w-full'

const PasswordGenerator = () => {
	const [password, setPassword] = useState('')
	const [passwordLength, setPasswordLength] = useState(12)
	const [passwordCopied, setPasswordCopied] = useState(false)

	useEffect(() => {
		handleGeneratePassword()
	}, [])

	useEffect(() => {
		if (passwordCopied) setTimeout(() => setPasswordCopied(false), 3000)
	}, [passwordCopied])

	function handleCopy() {
		setPasswordCopied(copyPassword(password))
	}

	function handleGeneratePassword() {
		let charactersAvaliable = ''
		// TODO: if from checkbox
		charactersAvaliable += NUMBERS
		charactersAvaliable += LOWER_CASE
		charactersAvaliable += UPPER_CASE
		charactersAvaliable += SPECIAL

		setPassword(getRandomPassword(charactersAvaliable, passwordLength))
	}

	return (
		<>
			<h2 className='flex justify-center my-4 mt-0 font-medium leading-tight text-4xl text-cyan-500'>
				Password Generator
			</h2>
			<div className='border border-white rounded-lg p-8 flex flex-col gap-y-4'>
				<div className='flex gap-2'>
					<label
						type='text'
						className='rounded-lg outline-0 py-2 px-2 text-gray-800 bg-white text-center w-96'
					>
						{password}
					</label>
					<button onClick={handleCopy} className={hover1Style}>
						<span className={`${hover2Style} py-2 px-2`}>
							<CopySvg />
						</span>
					</button>
				</div>
				<label className='flex justify-center gap-2'>
					<span>Password length:</span>
					<span className='text-cyan-500 font-bold'>{passwordLength}</span>
				</label>
				<input
					className='mb-4 accent-cyan-500'
					type='range'
					min='1'
					max='30'
					value={passwordLength}
					onChange={({ target: { value } }) => {
						setPasswordLength(value)
					}}
				/>

				<button onClick={handleGeneratePassword} className={hover1Style}>
					<span className={`${hover2Style} py-2 px-2`}>Generate password</span>
				</button>
			</div>

			<div
				className={`mt-6 transition-opacity duration-1000 ${
					passwordCopied ? 'opacity-1' : 'opacity-0'
				}`}
			>
				<div
					className='flex items-center p-4 space-x-4 w-full max-w-xs bg-white rounded-lg divide-x divide-gray-200 shadow dark:text-gray-400 dark:divide-gray-700 space-x dark:bg-gray-800'
					role='alert'
				>
					<div className='inline-flex flex-shrink-0 justify-center items-center w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200'>
						<svg
							aria-hidden='true'
							className='w-5 h-5'
							fill='currentColor'
							viewBox='0 0 20 20'
							xmlns='http://www.w3.org/2000/svg'
						>
							<path
								fillRule='evenodd'
								d='M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z'
								clipRule='evenodd'
							></path>
						</svg>
						<span className='sr-only'>Check icon</span>
					</div>
					<div className='pl-4 text-sm font-normal text-white'>Password copied successfully.</div>
				</div>
			</div>
		</>
	)
}

export default PasswordGenerator
