// src/components/david-ponc/input-range.svelte
<script lang="ts">
	export let length: number
</script>

<fieldset class="flex flex-col gap-2 my-4">
	<div class="flex items-center justify-between gap-4">
		<label for="" class="text-zinc-400">Longitud</label>
		<span class="text-indigo-300 drop-shadow-md shadow-indigo-100 font-medium font-sans text-xl">
			{length}
		</span>
	</div>
	<input
		min="8"
		step="2"
		max="128"
		type="range"
		bind:value={length}
		class="appearance-none rounded-md bg-white/10 h-2 accent-zinc-300 active:accent-zinc-600 hover:accent-zinc-400"
	/>
</fieldset>

// src/components/juanpablo-is/components/common/options/InputRange.jsx
const InputRange = ({ id, title, value, onChange, min = 1, max = 10, step = 1 }) => {
	return (
		<div className='my-2 flex items-center w-full gap-4 flex-col sm:flex-row'>
			<div className='flex items-center'>
				<p className='whitespace-nowrap text-lg text-gray-500 lg:text-xl dark:text-gray-400 font-bold'>
					{title}: <span className='px-5 font-normal'>{value}</span>
				</p>
			</div>

			<input
				id={id}
				className='w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 overflow-hidden py-2'
				type='range'
				value={value}
				step={step}
				min={min}
				max={max}
				onChange={(e) => onChange(e.target.value)}
			/>
		</div>
	)
}

export default InputRange
