// src/components/marsidev/components/Checkbox.tsx
/** @jsxImportSource solid-js */
import type { Component, JSX } from 'solid-js'
import '@components/marsidev/styles/checkbox.css'

// interface CheckboxProps extends ComponentProps<'input'> {
interface CheckboxProps {
	checked: boolean
	onChange: JSX.EventHandlerUnion<HTMLInputElement, InputEvent>
	id: string
	label: string
	disabled: boolean
}

export const Checkbox: Component<CheckboxProps> = (props) => {
	return (
		<div class='marsidev-checkbox flex items-center'>
			<input
				type='checkbox'
				id={props.id}
				onInput={props.onChange}
				checked={props.checked}
				disabled={props.disabled}
			/>
			<label class='cursor-pointer text-[1rem]' for={props.id}>
				{props.label}
			</label>
		</div>
	)
}

// src/components/franciscodiazpaccot73/Checkbox/index.jsx
import React from "react";

import { getCheckboxLabel } from "../utils";

import './styles.css'

const Checkbox = ({ id, checked, onCheck }) =>
	<div className="flex items-center">
		<input onChange={() => {}} type="checkbox" className="checkbox-input hidden" checked={checked} />
		<label>
			<span onClick={() => onCheck(id)} style={{ border: '1px solid #d97706' }} className="h-4 w-4 checkbox cursor-pointer rounded inline-block relative" />
		</label>
		<span onClick={() => onCheck(id)} className="cursor-pointer text-sm text-amber-600 h-6 ml-2">{getCheckboxLabel[id]}</span>
	</div>
	
export default Checkbox;
