// src/components/breinerjt/Slider.jsx
import React, { useState } from 'react'
import './Slider.css'

export const Slider = ({ min, max, setPasswordLength }) => {
	const [value, setValue] = useState(min)
	const isEqualToMinOrMax = value == min || value == max

	const onSlideValueChange = ({ target }) => {
		const value = target.value

		setValue(value)
		setPasswordLength(curr => ({
			...curr,
			passwordlength: value
		}))
	}

	return (
		<div className='mb-4'>
			<input
				aria-label='Password length'
				max={max}
				min={min}
				onChange={onSlideValueChange}
				type='range'
				value={value}
			/>
			<div className='flex justify-between'>
				<h6 className='text-lg font-bold'>{min}</h6>
				{ !isEqualToMinOrMax && <h6 className='text-lg font-bold'>{value}</h6> }
				<h6 className='text-lg font-bold'>{max}</h6>
			</div>
		</div>
	)
}

// src/components/yesiddev/atoms/Slider.svelte
<script>
	export let value
</script>

<div class="flex flex-col">
	<label for="slider" class="text-white font-semibold py-4">Length: Min 8 - Max 22</label>
	<input id="slider" name="slider" class="mb-2" type="range" min="8" max="22" bind:value />
	<output
		class="text-center text-white text-2xl bg-slate-800 w-16 m-auto rounded-md py-1"
		for="slider">{value}</output
	>
</div>
