// src/components/DaviidMM/Button/index.jsx
import React from 'react'

const colorClasses = {
	violet: 'bg-gradient-to-br from-purple-400 via-purple-500 to-purple-700 bg-size-200 bg-pos-0 hover:bg-pos-100 hover:text-white transition-all duration-500'
}

const Button = ({ children, className, color = 'violet', onClick }) => {
	return <button className={(className ? className + ' ' : '') + colorClasses[color] + ' ' + ' font-semibold px-4 py-2 w-fit rounded-lg'} onClick={onClick}>
		{children}
	</button>
}

export default Button

// src/components/samarjaffal/Button.svelte
<button
    type="button"
    class="font-special bg-gradient-to-r from-amber-400 via-blue-400 to-purple-400 text-body text-lg font-bold uppercase rounded mt-10 p-5 w-full transition ease-in-out duration-300 hover:rotate-2 hover:-translate-y-2 hover:scale-105"
    on:click>
    Generar Clave
</button>
