// src/components/Andresargote/Password.jsx
import { useState } from 'react'

export function Password({ password }) {
	const [isCopied, setIsCopied] = useState(false)

	const copyToClipboard = () => {
		navigator.clipboard.writeText(password)
		setIsCopied(true)
		setTimeout(() => setIsCopied(false), 1500)
	}

	return (
		<div className='bg-white flex items-center justify-between px-1 sm:px-6 py-3 rounded flex-wrap'>
			<output className='font-mono text-sm sm:text-2xl text-white text-gray-900'>{password}</output>
			<button
				className={`rounded-full px-2 md:px-3 py-1 border ${
					isCopied ? 'bg-green-500' : 'bg-black'
				} text-white text-sm font-mono p-0 ${
					!isCopied &&
					'hover:bg-white hover:border hover:text-black transition hover:ease-in duration-200'
				}`}
				aria-label='Copy'
				onClick={copyToClipboard}
			>
				{isCopied ? 'Copiado!' : 'Copiar'}
			</button>
		</div>
	)
}

// src/components/samarjaffal/Password.svelte
<script>
	import CopyButton from './CopyButton.svelte'

	export let password
	let copied = false

	function copyToClipboard({ password }) {
		navigator.clipboard.writeText(password).then(() => {
			copied = true
			setTimeout(() => {
				copied = false
			}, 1000)
		})
	}
</script>

<div class={`p-6 rounded mt-5 flex justify-between items-center ${copied ? 'copied' : ''}`}>
	<p
		class="font-light text-lg md:text-2xl bg-gradient-to-r from-amber-400 via-blue-400 to-purple-400 text-transparent bg-clip-text break-all"
	>
		{password}
	</p>
	<CopyButton {copied} on:click={() => copyToClipboard({ password })} />
</div>

<style>
	div {
		background: #170f1ee6;
		background: linear-gradient(to right, #170f1ee6 50%, #64e2ff 50%);
		background-size: 200% 100%;
		background-position: left bottom;
		transition: all 0.8s ease;
	}
	.copied {
		background-position: right bottom;
	}
</style>
