// src/components/tasiodev/PasswordGenerator.jsx
import { useState } from 'react'
import CopyIcon from './CopyIcon'
import Slider from './Slider'

export function PasswordGenerator() {
	const [password, setPassword] = useState(null)
	const [length, setLength] = useState(8)
	const [showCopied, setShowCopied] = useState(false)

	const generatePassword = () => {
		const TYPES = [
			'0123456789',
			'abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ',
			'!#$%&()*+,-./:;<=>?@[]^_{|}~'
		]
		let pwd = ''
		for (let i = 1; i <= length; i++) {
			const type = TYPES[i % 3]
			pwd += type[Math.floor(Math.random() * type.length)]
		}
		setPassword(pwd)
	}

	const copyHandler = () => {
		navigator.clipboard.writeText(password)
		setShowCopied(true)
		setTimeout(() => {
			setShowCopied(false)
		}, 2500)
	}

	return (
		<div className='text-white shadow-lg bg-gray-700 max-w-xl m-auto mt-20 p-6 rounded-lg'>
			<h1 className='text-center text-3xl font-bold my-4'>Password Generator</h1>
			<div className='flex gap-2 justify-center items-center'>
				<div className='w-5/6 p-2 min-h-[40px] bg-gray-500 text-gray-300 text-center rounded-sm break-all'>
					{password}
				</div>
				<div
					className={
						(password ? 'cursor-pointer' : 'cursor-not-allowed') +
						' w-1/6 p-2 rounded-md text-center flex justify-center bg-slate-600 relative shadow-md'
					}
					title='Copy to clipboard'
					onClick={() => password && copyHandler()}
				>
					<CopyIcon width={26} color={password ? 'white' : '#666'} />
					<div
						className='text-[12px] text-green-500 absolute top-[-20px] font-bold transition-all'
						style={{ opacity: showCopied ? 1 : 0 }}
					>
						COPIED!
					</div>
				</div>
			</div>
			<div>
				<Slider value={length} onChange={setLength} min={6} max={40} />
			</div>
			<div className='text-center'>
				<button
					onClick={generatePassword}
					className='my-4 bg-gray-900 text-center rounded-md py-2 w-28 m-auto cursor-pointer transition-all hover:-translate-y-1 shadow-md'
				>
					Generate!
				</button>
			</div>
		</div>
	)
}

// src/components/rogerparada/PasswordGenerator.vue
<template>
	<div class="w-96 h-56 border-white border-2 bg-white">
		<p class="text-3xl text-center mt-3">Password generator</p>
		<div class="row flex justify-center gap-0 mt-5 w-80 mx-auto">
			<input
				type="text"
				name="passwordBox"
				id="passwordBox"
				readonly
				class="p-1 border-2 border-gray-400 w-72"
				v-model="password"
			/>
			<button
				class="border-2 p-1 border-gray-400 bg-white hover:bg-black border-l-0"
				@click="copyPassword()"
			>
				<img alt="Copy" title="Copy" :src="iconCopy" class="w-8 h-8" />
			</button>
		</div>
		<div class="flex justify-center">
			<input type="range" name="" id="" v-model="passLength" class="w-80 mt-3" />
		</div>
		<div class="flex justify-center mt-3 text-white">
			<button @click="generatePassword()" class="bg-gray-500 p-3">Generate Password</button>
		</div>
		<div class="slider"></div>
	</div>
</template>

<script>
import { ref } from '@vue/reactivity'
import icon from './assets/images/copyIcon.svg'

export default {
	setup() {
		const password = ref('')
		const passLength = 8
		const iconCopy = icon
		return { password, passLength, iconCopy }
	},
	methods: {
		async copyPassword() {
			if (this.password === '') return
			await navigator.clipboard.writeText(this.password)
			alert(`Copied text: ${this.password}\nLength: ${this.password.length}`)
		},
		generatePassword() {
			let pass = ''
			for (let index = 0; index < this.passLength; index++) {
				pass += this.generateValidCharacter()
			}
			this.password = pass
		},
		generateValidCharacter() {
			const valid = [
				{ name: 'Capital', min: 65, max: 90 },
				{ name: 'Vowels', min: 97, max: 122 },
				{ symbols: '~`!@#$%^&*()_-+={[}]|:;"\'<,>.?/' }
			]
			const random = this.singleRandom(3)

			if (random === 0 || random === 1) {
				const { min, max } = valid[random]
				return String.fromCharCode(this.rangeRandom(min, max))
			}
			if (random === 2) {
				const { symbols } = valid[random]
				return symbols[this.singleRandom(symbols.length - 1)]
			}
			if (random === 3) {
				return this.singleRandom(9)
			}
		},
		singleRandom(maxValue) {
			return Math.floor(Math.random() * (maxValue + 1))
		},
		rangeRandom(minValue, maxValue) {
			return Math.floor(Math.random() * (maxValue - minValue) + minValue)
		}
	}
}
</script>

<style></style>
