// src/components/yesiddev/atoms/Checkbox.svelte
<script>
	export let label = ''
</script>

<div class="flex items-center pl-4 rounded-md border border-slate-400 my-2 hover:border-white duration-300">
	<input
		id={label}
		type="checkbox"
		value=""
		name="bordered-checkbox"
		class="w-4 h-4 appearance-none border rounded border-slate-400 checked:bg-blue-500 checked:border-transparent focus:outline-none"
	/>
	<label for={label} class="py-4 ml-2 w-full text-sm font-medium text-white cursor-pointer"
		>{label}</label
	>
</div>

// src/components/mkeOrt/components/Checkbox.vue
<script setup lang="ts">
import { computed } from '@vue/reactivity'

const props = defineProps(['modelValue', 'checkboxMessage', 'disabled'])
const emit = defineEmits(['update:modelValue', 'change'])

const value = computed({
	get() {
		return props.modelValue
	},
	set(value) {
		emit('update:modelValue', value)
	}
})
</script>

<template>
	<div class="w-full flex justify-between mb-3 items-center">
		<label class="w-full" :for="props.checkboxMessage">{{ props.checkboxMessage }}</label>
		<input
			:disabled="disabled"
			type="checkbox"
			class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
			:id="props.checkboxMessage"
			:value="checkboxMessage"
			v-model="value"
			@change="emit('change')"
		/>
	</div>
</template>

<style scoped>
.mke-checkbox:disabled {
	border: 8px solid gray !important;
	cursor: not-allowed;
}

.mke-checkbox:checked {
	border: 8px solid #ffcaca;
}
</style>
