// src/components/renatomendozac/components/Checkbox.svelte
<script>
	export let id
	export let checked
	export let disabled
</script>

<div class="checkbox-container">
	<input
		id={`checkbox-${id}`}
		{checked}
		value={id}
		{disabled}
		type="checkbox"
		on:change
	/>
	<label class="text-sm" for={`checkbox-${id}`}>
		<slot />
	</label>
</div>

<style>
	.checkbox-container {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	input[type=checkbox] {
		appearance: none;
		-webkit-appearance: none;
		-moz-appearance: none;
		height: 18px;
		width: 18px;
		display: flex;
		align-items: center;
		justify-content: center;
		background-color: rgb(155, 70, 89);
		border: 2px solid rgb(155, 70, 89);
		border-radius: 5px;
		cursor: pointer;
	}

	input[type=checkbox]::after {
		content: '\2713';
		color: rgb(155, 70, 89);
		font-weight: 900;
		display: none;
	}

	input[type=checkbox]:hover {
		border: 2px solid #4ADE80;
	}

	input[type=checkbox]:checked {
		border: 2px solid rgb(90, 214, 93);
		background-color: rgb(90, 214, 93);
	}

	input[type=checkbox]:checked::after {
		display: block;
	}

	input[type=checkbox]:disabled {
		opacity: 0.2;
	}

	label {
		cursor: pointer;
	}
</style>

// src/components/mkeOrt/components/Checkbox.vue
<script setup lang="ts">
import { computed } from '@vue/reactivity'

const props = defineProps(['modelValue', 'checkboxMessage', 'disabled'])
const emit = defineEmits(['update:modelValue', 'change'])

const value = computed({
	get() {
		return props.modelValue
	},
	set(value) {
		emit('update:modelValue', value)
	}
})
</script>

<template>
	<div class="w-full flex justify-between mb-3 items-center">
		<label class="w-full" :for="props.checkboxMessage">{{ props.checkboxMessage }}</label>
		<input
			:disabled="disabled"
			type="checkbox"
			class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
			:id="props.checkboxMessage"
			:value="checkboxMessage"
			v-model="value"
			@change="emit('change')"
		/>
	</div>
</template>

<style scoped>
.mke-checkbox:disabled {
	border: 8px solid gray !important;
	cursor: not-allowed;
}

.mke-checkbox:checked {
	border: 8px solid #ffcaca;
}

.mke-checkbox:checked::before {
	content: '✓';
	position: absolute;
	transform: translate(-50%, -50%);
	color: #251b37;
}
</style>
