// src/components/tasiodev/PasswordGenerator.jsx
import { useState } from 'react'
import CopyIcon from './CopyIcon'
import Slider from './Slider'

export function PasswordGenerator() {
	const [password, setPassword] = useState(null)
	const [length, setLength] = useState(8)
	const [showCopied, setShowCopied] = useState(false)

	const generatePassword = () => {
		const TYPES = [
			'0123456789',
			'abcdefghijklmnñopqrstuvwxyzABCDEFGHIJKLMNÑOPQRSTUVWXYZ',
			'!#$%&()*+,-./:;<=>?@[]^_{|}~'
		]
		let pwd = ''
		for (let i = 1; i <= length; i++) {
			const type = TYPES[i % 3]
			pwd += type[Math.floor(Math.random() * type.length)]
		}
		setPassword(pwd)
	}

	const copyHandler = () => {
		navigator.clipboard.writeText(password)
		setShowCopied(true)
		setTimeout(() => {
			setShowCopied(false)
		}, 2500)
	}

	return (
		<div className='text-white shadow-lg bg-gray-700 max-w-xl m-auto mt-20 p-6 rounded-lg'>
			<h1 className='text-center text-3xl font-bold my-4'>Password Generator</h1>
			<div className='flex gap-2 justify-center items-center'>
				<div className='w-5/6 p-2 min-h-[40px] bg-gray-500 text-gray-300 text-center rounded-sm break-all'>
					{password}
				</div>
				<div
					className={
						(password ? 'cursor-pointer' : 'cursor-not-allowed') +
						' w-1/6 p-2 rounded-md text-center flex justify-center bg-slate-600 relative shadow-md'
					}
					title='Copy to clipboard'
					onClick={() => password && copyHandler()}
				>
					<CopyIcon width={26} color={password ? 'white' : '#666'} />
					<div
						className='text-[12px] text-green-500 absolute top-[-20px] font-bold transition-all'
						style={{ opacity: showCopied ? 1 : 0 }}
					>
						COPIED!
					</div>
				</div>
			</div>
			<div>
				<Slider value={length} onChange={setLength} min={6} max={40} />
			</div>
			<div className='text-center'>
				<button
					onClick={generatePassword}
					className='my-4 bg-gray-900 text-center rounded-md py-2 w-28 m-auto cursor-pointer transition-all hover:-translate-y-1 shadow-md'
				>
					Generate!
				</button>
			</div>
		</div>
	)
}

// src/components/mkeOrt/components/PasswordGenerator.vue
<script setup lang="ts">
import ClipboardIcon from './ClipboardIcon.vue'
import {
	VALID_CHARACTERS_TO_USE,
	usePasswordGeneratorRepository
} from '../composables/password-generator-repository'

const {
	charactersToUse,
	copied,
	copyToClipboard,
	generatePassword,
	onSelectedCharactersChange,
	password,
	range
} = usePasswordGeneratorRepository()
</script>

<template>
	<div class="h-screen w-screen flex justify-center items-center">
		<div class="w-80 bg-[#251b37] text-[#ffcaca] rounded-lg px-7 pt-10 pb-3">
			<div class="relative">
				<div class="w-full rounded-t-lg p-5 grid grid-cols-6 gap-2 absolute bottom-0 bg-[#372948]">
					<div class="col-span-5 max-w-xs break-all">
						{{ password }}
					</div>
					<div class="flex justify-end items-end">
						<ClipboardIcon @copy-to-clipboard="copyToClipboard" />
					</div>
				</div>
			</div>
			<button
				v-if="!copied"
				id="mke-generate-btn"
				class="w-full rounded-b-lg py-2 bg-[#372948] border-t-[0.5px] border-solid border-[#251b37]"
				@click="generatePassword"
			>
				Generate
			</button>
			<div
				v-if="copied"
				class="w-full rounded-b-lg py-2 bg-[#ffcaca] text-[#251b37] border-t-[0.5px] border-solid border-[#251b37] flex justify-center"
			>
				Copied!
			</div>
			<div class="flex items-center justify-between mt-5">
				<small class="font-bold">5</small>
				<input
					type="range"
					id="mke-range"
					class="w-full appearance-none h-1 bg-[#372948] outline-none mt-0 mx-3"
					v-model="range"
					min="5"
					max="128"
					@input="generatePassword"
				/>
				<small class="font-bold">128</small>
			</div>
			<div class="flex justify-end text-xs">
				<small>{{ range }}</small>
			</div>
			<div class="mt-1">
				<div class="w-full flex justify-between py-3 items-center">
					<label class="w-full" for="a-z">{{ VALID_CHARACTERS_TO_USE.LOWERCASE }}</label>
					<input
						type="checkbox"
						class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
						id="a-z"
						:value="VALID_CHARACTERS_TO_USE['LOWERCASE']"
						v-model="charactersToUse"
						:disabled="
							charactersToUse.length <= 1 &&
							charactersToUse.includes(VALID_CHARACTERS_TO_USE['LOWERCASE'])
						"
						@change="onSelectedCharactersChange"
					/>
				</div>
				<div class="w-full flex justify-between mb-3 items-center">
					<label class="w-full" for="A-Z">{{ VALID_CHARACTERS_TO_USE.UPPERCASE }}</label>
					<input
						type="checkbox"
						class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
						id="A-Z"
						:value="VALID_CHARACTERS_TO_USE.UPPERCASE"
						v-model="charactersToUse"
						:disabled="
							charactersToUse.length <= 1 &&
							charactersToUse.includes(VALID_CHARACTERS_TO_USE.UPPERCASE)
						"
						@change="onSelectedCharactersChange"
					/>
				</div>
				<div class="w-full flex justify-between mb-3 items-center">
					<label class="w-full" for="0-9">{{ VALID_CHARACTERS_TO_USE.NUMBERS }}</label>
					<input
						type="checkbox"
						class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
						id="0-9"
						:value="VALID_CHARACTERS_TO_USE.NUMBERS"
						v-model="charactersToUse"
						:disabled="
							charactersToUse.length <= 1 &&
							charactersToUse.includes(VALID_CHARACTERS_TO_USE.NUMBERS)
						"
						@change="onSelectedCharactersChange"
					/>
				</div>
				<div class="w-full flex justify-between mb-3 items-center">
					<label class="w-full" for="!@#$%^&*">{{
						VALID_CHARACTERS_TO_USE.SPECIAL_CHARACTERS
					}}</label>
					<input
						type="checkbox"
						class="mke-checkbox h-2.5 w-2.5 appearance-none rounded-md outline-none border-8 border-solid border-white"
						id="!@#$%^&*"
						:value="VALID_CHARACTERS_TO_USE.SPECIAL_CHARACTERS"
						v-model="charactersToUse"
						:disabled="
							charactersToUse.length <= 1 &&
							charactersToUse.includes(VALID_CHARACTERS_TO_USE.SPECIAL_CHARACTERS)
						"
						@change="onSelectedCharactersChange"
					/>
				</div>
			</div>
		</div>
	</div>
</template>

<style scoped>
#mke-generate-btn:active {
	color: #372948;
}

.mke-checkbox:disabled {
	border: 8px solid gray !important;
	cursor: not-allowed;
}

.mke-checkbox:checked {
	border: 8px solid #ffcaca;
}

#mke-range::-webkit-slider-thumb {
	appearance: none;
	width: 15px;
	height: 15px;
	background: #ffcaca;
	cursor: grab;
	border-radius: 50%;
	border: none;
}

#mke-range::-webkit-slider-thumb:active {
	cursor: grabbing;
}

#mke-range::-moz-range-thumb {
	width: 15px;
	height: 15px;
	background: #ffcaca;
	cursor: grab;
	border-radius: 50%;
	border: none;
}

#mke-range::-moz-range-thumb:active {
	cursor: grabbing;
}
</style>
