// src/components/yesiddev/atoms/Slider.svelte
<script>
	export let value
</script>

<div class="flex flex-col">
	<label for="slider" class="text-white font-semibold py-4">Length: Min 8 - Max 22</label>
	<input id="slider" name="slider" class="mb-2" type="range" min="8" max="22" bind:value />
	<output
		class="text-center text-white text-2xl bg-slate-800 w-16 m-auto rounded-md py-1"
		for="slider">{value}</output
	>
</div>

// src/components/wayaba/Slider.jsx

const Slider = ({ value, min, max, onChange }) => {
	const handleOnChange = (event) => {
		onChange(event)
	}
	return (
		<div className='flex justify-center items-center gap-3'>
			<input
				className='my-4 accent-[#3CB371]'
				type='range'
				min={min}
				max={max}
				value={value}
				onChange={handleOnChange}
			/>
			<div className='w-12 rounded-lg bg-[#3CB371] text-white text-center font-bold leading-3 px-1 py-3'>
				{value}
			</div>
		</div>
	)
}

export default Slider
