// src/components/victormarcas/PasswordGenerator.vue
<script setup>
import { ref } from 'vue'
import Layout from './Layout.vue'
import CopyIcon from './icons/CopyIcon.vue'
import ArrowRightIcon from './icons/ArrowRightIcon.vue'
const minLenghtPassword = 6
const maxLenghtPassword = 20
const characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()'
const showMessageClipboard = ref(false)
const password = ref('')
const rangeLenghtPassword = ref(minLenghtPassword)

const handleGeneratePassword = () => {
	password.value = Array.from({ length: rangeLenghtPassword.value })
		.map(() => characters.charAt(Math.floor(Math.random() * characters.length)))
		.join('')
}

const handleCopyPassword = () => {
	navigator.clipboard.writeText(password.value).then(() => {
		showMessageClipboard.value = true
		const timeout = window.setTimeout(() => {
			showMessageClipboard.value = false
			window.clearTimeout(timeout)
		}, 1000)
	})
}
</script>
<template>
	<Layout>
		<template #title>Password Generator</template>
		<template #content>
			<form @submit.prevent="handleGeneratePassword">
				<div class="flex gap-4 items-end">
					<div class="flex-grow">
						<label for="minmax-range" class="block py-2 text-sm font-medium text-gray-300"
							>Character Length</label
						>
						<input
							id="minmax-range"
							type="range"
							v-model="rangeLenghtPassword"
							:min="minLenghtPassword"
							:max="maxLenghtPassword"
							class="w-full h-2 bg-gray-800 rounded-lg appearance-none cursor-pointer"
						/>
					</div>
					<div class="font-bold w-14 text-right text-3xl text-[#5FE79C]">
						{{ rangeLenghtPassword }}
					</div>
				</div>
				<div class="flex items-center gap-4 mt-4">
					<div class="relative flex-1">
						<input
							type="text"
							v-model="password"
							readonly
							placeholder="P4$5W0rD!"
							class="rounded w-full border border-[#222528] p-4 leading-6 text-base focus:outline-none placeholder:text-gray-500 text-gray-400 bg-transparent"
						/>
						<transition
							enter-active-class="transition-all duration-150 transform ease-out-quad"
							leave-active-class="transition-all duration-200 transform ease-in-quad"
							enter-class="opacity-0"
							enter-to-class="opacity-100"
							leave-class="opacity-100"
							leave-to-class="opacity-0"
							appear
						>
							<span
								v-if="showMessageClipboard"
								class="absolute inset-x-0 top-full mt-1 text-[#5FE79C] text-xs"
								>Copied to clipboard</span
							>
						</transition>
					</div>
					<button
						type="button"
						class="shrink-0 inline-flex items-center justify-center text-[#5FE79C] disabled:text-gray-700 hover:scale-110 cursor-pointer transition-all duration-300 ease-in-out disabled:scale-100 focus:outline-none"
						@click="handleCopyPassword"
						:disabled="!password"
					>
						<CopyIcon class="w-8 h-8" />
					</button>
				</div>
				<button
					type="submit"
					class="flex w-full gap-4 rounded mt-7 uppercase text-base text-[#111418] items-center font-bold justify-center leading-6 py-3 px-6 bg-[#5FE79C] hover:bg-[#5FE79C]/95 transition-colors focus:outline-none"
				>
					Generate
					<ArrowRightIcon class="w-4 h-4" />
				</button>
			</form>
		</template>
	</Layout>
</template>
<style>
input[type='range']::-webkit-slider-thumb {
	-webkit-appearance: none;
	appearance: none;
	width: 20px;
	height: 20px;
	border-radius: 50%;
	background: #5fe79c;
	cursor: pointer;
}
</style>

// src/components/bloodboy21/PasswordGenerator.jsx
import React from 'react'
import storage from '../bloodboy21/Options'

const optionsList = {
	numbers: 'Numbers',
	symbols: 'Symbols'
}

const Options = ({ optionHandler, options }) => {
	return Object.entries(optionsList).map(([option, title]) => {
		return (
			<li key={option} className='flex  justify-center '>
				<input
					type='checkbox'
					name={option}
					id={option}
					checked={options[option]}
					onChange={optionHandler}
					className='align-top mr-2 accent-blue-600 w-4 h-4 border-gray-300 duration-150 ease-in-out focus:ring-blue-500 inline-block mt-1 cursor-pointer'
				/>
				<label htmlFor={option} className='form-check-label inline-block '>
					{title}
				</label>
			</li>
		)
	})
}

const SizeSlider = ({ options, setLength }) => {
	return (
		<div className='w-full'>
			<label
				htmlFor='password-length'
				className='block mb-2 text-sm font-medium text-gray-900 dark:text-blue-300'
			>
				Length: {options.length}
			</label>
			<input
				id='password-length'
				type='range'
				min='8'
				max='64'
				className='w-full h-2 bg-blue-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 accent-blue-600 '
				value={options.length}
				onChange={setLength}
			/>
		</div>
	)
}

const Alert = ({ alert, setAlert }) => {
	setTimeout(() => {
		setAlert({
			...alert,
			show: false
		})
	}, 5000)
	const alertType =
		{
			success: 'green',
			error: 'red',
			warning: 'yellow'
		}[alert.type] || 'blue'
	return (
		<div
			className={`${
				alert.show ? 'flex' : 'hidden'
			} fixed top-0 right-0 w-full h-full justify-end items-start z-50 transition-all duration-300 ease-linear`}
		>
			<div className='bg-slate-800 w-72 rounded-lg p-3 flex flex-col gap-1 align-top mt-2 mr-3 transition-all first-letter:uppercase'>
				<h3 className={`text-xl font-bold text-${alertType}-500`}>{alert.title}</h3>
				<p className='text-slate-100'>{alert.message}</p>
			</div>
		</div>
	)
}

function PasswordGenerator () {
	const { options, setOptions, createPassword, password, setPassword, alert, setAlert } = storage()
	const optionHandler = (e) => {
		const { name, checked } = e.target
		setOptions({ ...options, [name]: checked })
	}

	const passwordHandler = () => setPassword(createPassword())
	const setLength = (e) => setOptions({ ...options, length: e.target.value })
	const copyToClipboard = () => {
		navigator.clipboard.writeText(password)
		setAlert({
			show: true,
			title: 'Success',
			message: 'Password copied to clipboard',
			type: 'success'
		})
	}
	return (
		<main className='flex flex-col text-white justify-center items-center w-full gap-2'>
			<Alert alert={alert} setAlert={setAlert} />
			<h2 className='text-xl font-bold mt-3'>Password generator</h2>
			<section className='flex flex-wrap m-4  justify-center  box-border w-full lg:w-1/3 h-auto'>
				<input
					type='text'
					value={password}
					className='rounded-lg px-2 py-1 bg-transparent w-auto lg:w-full h-auto text-xl font-bold text-white border-2 border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent font-sans'
					readOnly
				/>
			</section>
			<section className='flex gap-2 w-full justify-center'>
				<button
					onClick={passwordHandler}
					className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-1 rounded focus:shadow-outline '
				>
					Generate
				</button>
				<button
					className='bg-slate-500 hover:bg-slate-700 text-white font-bold py-1 px-2 rounded  focus:shadow-outline '
					onClick={copyToClipboard}
				>
					Copy
				</button>
			</section>
			<section className='flex justify-center w-full overflow-hidden mt-3 font-special'>
				<div className='flex flex-col w-[85%] lg:w-1/3 rounded-lg justify-center  bg-slate-800 gap-3 p-3'>
					<SizeSlider options={options} setLength={setLength} />
					<div className='w-full flex align-baseline justify-start '>
						<ul className='flex  gap-3 align-baseline items-baseline'>
							<Options options={options} optionHandler={optionHandler} />
						</ul>
					</div>
				</div>
			</section>
		</main>
	)
}

export default PasswordGenerator
