// src/components/yesiddev/atoms/Slider.svelte
<script>
	export let value
</script>

<div class="flex flex-col">
	<label for="slider" class="text-white font-semibold py-4">Length: Min 8 - Max 22</label>
	<input id="slider" name="slider" class="mb-2" type="range" min="8" max="22" bind:value />
	<output
		class="text-center text-white text-2xl bg-slate-800 w-16 m-auto rounded-md py-1"
		for="slider">{value}</output
	>
</div>

// src/components/tasiodev/Slider.jsx
import React from 'react'

export default function Slider ({ value, onChange, min, max }) {
	return <div className='text-center my-6'>
		<input
			className='w-full max-w-lg'
			type='range'
			min={min || 1}
			max={max || 100}
			value={value}
			onChange={e => onChange(e.target.value)} />
		<div>Length: {value}</div>
	</div>
}
