// src/components/david-ponc/input-range.svelte
<script lang="ts">
	export let length: number
</script>

<fieldset class="flex flex-col gap-2 my-4">
	<div class="flex items-center justify-between gap-4">
		<label for="" class="text-zinc-400">Longitud</label>
		<span class="text-indigo-300 drop-shadow-md shadow-indigo-100 font-medium font-sans text-xl">
			{length}
		</span>
	</div>
	<input
		min="8"
		step="2"
		max="128"
		type="range"
		bind:value={length}
		class="appearance-none rounded-md bg-white/10 h-2 accent-zinc-300 active:accent-zinc-600 hover:accent-zinc-400"
	/>
</fieldset>

// src/components/juanpablo-is/components/InputRange.jsx
import { useContext } from 'react'
import passwordContext from '../context/PasswordContext'

const InputRange = () => {
	const { passwordLength, setPasswordLength } = useContext(passwordContext)

	return (
		<div className='my-2 flex items-center w-full gap-4 flex-col sm:flex-row'>
			<div className='flex items-center'>
				<p className='whitespace-nowrap text-lg text-gray-500 lg:text-xl dark:text-gray-400 font-bold'>
					Password length: <span className='px-5 font-normal'>{passwordLength}</span>
				</p>
			</div>

			<input
				id='default-range'
				className='w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700'
				type='range'
				value={passwordLength}
				step={1}
				min={1}
				max={50}
				onChange={(e) => setPasswordLength(e.target.value)}
			/>
		</div>
	)
}

export default InputRange
