// src/components/krrskl/Footer.svelte
<footer class="mt-3">
	<p>
		Figma file <a
			href="https://www.figma.com/file/l2nKcgxqI5gYscN8cez3O5/hacktoberfest-2022"
			target="_blank"
			rel="noopener noreferrer"><strong>here</strong></a
		>
		<br />
		<br />
		Made with ❤️ by <strong>Rubén Carrascal</strong> using <strong>Svelte</strong>
	</p>
</footer>

<style>
	footer {
		text-align: center;
		color: var(--krrskl-white-color);
	}
</style>

// src/components/znareak/components/Footer/index.jsx
import React from 'react'
import css from './footer.module.css'

export default function Footer() {
	return (
		<footer className={css.footer}>
			<a href='https://www.twitch.tv/midudev' rel='noopener noreferrer' target='_blank'>
				midudev
			</a>
			<a href='https://libardo.vercel.app/' rel='noopener noreferrer' target='_blank'>
				znareak
			</a>
			<a href='https://hacktoberfest.com/' rel='noopener noreferrer' target='_blank'>
				hacktoberfest
			</a>
			<a
				href='https://github.com/midudev/password-generator'
				rel='noopener noreferrer'
				target='_blank'
			>
				github
			</a>
		</footer>
	)
}
