// src/components/fredoist/CopyButton.svelte
<script type="ts">
	import { usePassword } from '@hooks/fredoist/use-password'

	const password = usePassword()

	async function copyPassword(e: Event) {
		e.preventDefault()
		await navigator.clipboard.writeText($password)
	}
</script>

<button
	type="button"
	class="relative bg-[#f8ef00] text-black font-semibold uppercase py-5 px-10 border-r-2 border-[#ff003c] inline-flex items-center justify-between gap-x-16 [clip-path:polygon(100%_0,100%_25%,100%_100%,6%_100%,0%_70%,0_0)]"
	on:click={copyPassword}
>
	<span>Copy Password_</span>
	<span class="absolute bg-black right-5 -bottom-px text-xs font-normal font-[Barlow,sans-serif] leading-none pl-2 pr-5 text-[#fafafa] border-l-2 border-[#ff003c]">R25</span>
	<svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" viewBox="0 0 512 512">
		<path
			fill="none"
			stroke="currentColor"
			stroke-linecap="square"
			stroke-miterlimit="10"
			stroke-width="48"
			d="M268 112l144 144-144 144M392 256H100"
		/>
	</svg>
</button>

// src/components/ivanlolivier/CopyButton.jsx
import React from 'react'

const CopyButton = ({ text }) => {
	const copyToClipboard = () => {
		navigator.clipboard.writeText(text)
	}

	return (
		<button
			className='flex items-center py-2 px-3 text-xs font-medium text-gray-600 bg-gray-100 border-l border-gray-200 dark:border-gray-600 dark:text-gray-400 dark:bg-gray-800 hover:text-blue-700 dark:hover:text-white copy-to-clipboard-button hover:bg-gray-700 active:bg-gray-600 focus:outline-none'
			onClick={copyToClipboard}
		>
			<svg className='mr-2 w-4 h-4' fill='none' stroke='currentColor' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>
				<path strokeLinecap='round' strokeLinejoin='round' strokeWidth='2' d='M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z'></path>
			</svg>
			<span className='copy-text'>Copy</span>
		</button>
	)
}

export default CopyButton
