// src/components/carlosfernandezcabrero/CopyButton.svelte
<script>
	export let textToCopy

	function copyToClipboard() {
		const modalContainer = document.querySelector('#modal')

		navigator.clipboard.writeText(textToCopy)
		modalContainer.classList.remove('hide')
		modalContainer.classList.add('show')

		setTimeout(() => {
			modalContainer.classList.remove('show')
			modalContainer.classList.add('hide')
		}, 2_000)
	}
</script>

<button
	class="p-4 rounded-full bg-[#29BB89] border-4 border-[#29BB89] hover:bg-[#289672] active:bg-[#1E6F5C] active:border-[#1E6F5C]"
	on:click={copyToClipboard}
	aria-label="Copy to clipboard"
>
	<svg
		xmlns="http://www.w3.org/2000/svg"
		class="h-10 w-10"
		viewBox="0 0 24 24"
		stroke-width="2"
		stroke="currentColor"
		fill="none"
		stroke-linecap="round"
		stroke-linejoin="round"
	>
		<path stroke="none" d="M0 0h24v24H0z" fill="none" />
		<rect x="8" y="8" width="12" height="12" rx="2" />
		<path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2" />
	</svg>
</button>

// src/components/ivanlolivier/CopyButton.jsx
import React from 'react'

const CopyButton = ({ text }) => {
	const copyToClipboard = () => {
		navigator.clipboard.writeText(text)
	}

	return (
		<button
			className='flex items-center py-2 px-3 text-xs font-medium text-gray-600 bg-gray-100 border-l border-gray-200 dark:border-gray-600 dark:text-gray-400 dark:bg-gray-800 hover:text-blue-700 dark:hover:text-white copy-to-clipboard-button hover:bg-gray-700 active:bg-gray-600 focus:outline-none'
			onClick={copyToClipboard}
		>
			<svg className='mr-2 w-4 h-4' fill='none' stroke='currentColor' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>
				<path strokeLinecap='round' strokeLinejoin='round' strokeWidth='2' d='M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z'></path>
			</svg>
			<span className='copy-text'>Copy</span>
		</button>
	)
}

export default CopyButton
