// src/components/samarjaffal/Slider.svelte
<script>
	export let settings
</script>
	
<fielset>
	<input type="range" class="w-full mt-6 slider" min="8" max="20" bind:value={settings.length} />
	<p class="text-white font-bold text-3xl md:text-4xl text-center">{settings.length}</p>
</fielset>

<style>
	.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 25px;
  background: #ffe27d;
  outline: none;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 25px;
  height: 25px;
  background: #64e2ff;
  cursor: pointer;
	-webkit-transition: .2s;
  transition: background-color ease-in-out .2s;
}

.slider::-webkit-slider-thumb:hover{
	background-color: #9092ff	
}

.slider::-moz-range-thumb {
  width: 25px;
  height: 25px;
  background: #04AA6D;
  cursor: pointer;
}
</style>

// src/components/renatomendozac/components/Slider.vue
<script setup>
import { ref } from 'vue'
import { formStore } from '@components/renatomendozac/store'

const CharacterLength = ref('4')

function onChange(event) {
	const rangeValue = event.target.value
	CharacterLength.value = rangeValue

	formStore.update({ length: parseInt(rangeValue) })
}
</script>

<template>
	<input class="slider" type="range" :value="CharacterLength" min="4" max="20" @change="onChange" />
</template>

<style>
.slider {
	-webkit-appearance: none;
	appearance: none;
	width: 100%;
	height: 6px;
	background: #c92626c7;
	outline: none;
	opacity: 0.7;
	-webkit-transition: 0.2s;
	transition: opacity 0.2s;
	border-radius: 1px;
}

.slider:hover {
	opacity: 1;
}

.slider::-webkit-slider-thumb {
	-webkit-appearance: none;
	appearance: none;
	width: 18px;
	height: 18px;
	background: #04ff53;
	cursor: pointer;
	border-radius: 12px;
}

.slider::-moz-range-thumb {
	width: 18px;
	height: 18px;
	background: #04ff53;
	cursor: pointer;
	border-radius: 12px;
}
</style>
