// src/components/samarjaffal/Button.svelte
<button
    type="button"
    class="font-special bg-gradient-to-r from-amber-400 via-blue-400 to-purple-400 text-body text-lg font-bold uppercase rounded mt-10 p-5 w-full transition ease-in-out duration-300 hover:rotate-2 hover:-translate-y-2 hover:scale-105"
    on:click>
    Generar Clave
</button>

// src/components/marsidev/components/Button.tsx
/** @jsxImportSource solid-js */
import type { Component, JSX } from 'solid-js'

interface ButtonsProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
	caption: string
	handleClick: () => void
	foo?: string
}

export const Button: Component<ButtonsProps> = ({ caption, handleClick }) => {
	return (
		<button
			onclick={handleClick}
			class='w-auto min-w-[180px] rounded-[60px] bg-[#9F7AEA] py-2 px-4 text-lg font-bold leading-8 text-white transition duration-150 ease-in-out hover:scale-105 hover:brightness-90 focus:outline-slate-400 active:scale-95'
		>
			{caption}
		</button>
	)
}
