// src/components/samarjaffal/CopyButton.svelte
<script>
	export let copied
</script>
<button type="button" id="copy-button" on:click>
	{#if copied}
		<svg width="48px" height="48px" stroke-width="1.72" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#000000"><path d="M1.5 12.5l4.076 4.076a.6.6 0 00.848 0L9 14M16 7l-4 4" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round"></path><path d="M7 12l4.576 4.576a.6.6 0 00.848 0L22 7" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round"></path>
		</svg>
	{:else}
		<svg width="48px" height="48px" stroke-width="1.72" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#ffffff"><path d="M19.4 20H9.6a.6.6 0 01-.6-.6V9.6a.6.6 0 01.6-.6h9.8a.6.6 0 01.6.6v9.8a.6.6 0 01-.6.6z" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round" stroke-linejoin="round"></path><path d="M15 9V4.6a.6.6 0 00-.6-.6H4.6a.6.6 0 00-.6.6v9.8a.6.6 0 00.6.6H9" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round" stroke-linejoin="round"></path>
		</svg>
	{/if}
</button>

// src/components/tommdq/CopyButton.jsx
import React from 'react'

const CopyButton = ({ copyPassword }) => {
	return (
		<button onClick={copyPassword} className='outline-none'>
			<svg
				xmlns='http://www.w3.org/2000/svg'
				className='icon icon-tabler icon-tabler-copy hover:stroke-[#a7a7cc] transition duration-300 hover:ease-in-out hover:scale-110'
				width='44'
				height='44'
				viewBox='0 0 24 24'
				strokeWidth='1.5'
				stroke='#E4842E'
				fill='none'
				strokeLinecap='round'
				strokeLinejoin='round'
			>
				<path stroke='none' d='M0 0h24v24H0z' fill='none' />
				<rect x='8' y='8' width='12' height='12' rx='2' />
				<path d='M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2' />
			</svg>
		</button>
	)
}

export default CopyButton
