// src/components/brayanbasallo/input/checkbox.vue
<template>
	<div class="flex items-start">
		<div class="flex items-center h-5">
			<input
				:id="id"
				type="checkbox"
				v-model="detail.active"
				value=""
				class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800"
			/>
		</div>
		<label :for="id" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-400">
			{{ detail.title }}
		</label>
	</div>
</template>

<script>
export default {
	name: 'checkbox',
	props: {
		detail: {
			required: true,
			type: Object
		},
		id: {
			required: true,
			type: String
		}
	}
}
</script>

<style scoped></style>

// src/components/josedefreitas91/Checkbox.jsx
import { useState } from 'react'

export default function Checkbox({ checked, onChange, children }) {
	const [check, setCheck] = useState(checked)

	const handleChange = () => {
		setCheck((prevCheck) => !prevCheck)
		onChange()
	}

	return (
		<div className='flex items-center'>
			<input
				checked={check}
				onChange={handleChange}
				type='checkbox'
				className='w-4 h-4 text-blue-600 bg-gray-100 rounded border-gray-300 focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600'
			/>
			<label className='ml-2 text-sm font-medium text-gray-900 dark:text-gray-300'>
				{children}
			</label>
		</div>
	)
}
