// src/components/accieo/PasswordGenerator.svelte
<script>
	
	import CopyIcon from '@components/accieo/CopyIcon.svelte';

	let passwordLength = 12;
	let password = '';

	function getRandomChar() {
		const LETTERS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
		const NUMBERS = '0123456789';
		const SYMBOLS = '!*#?+=-_@$&';
		
		const randomInt = Math.floor(Math.random() * 11);
		
		// 60-20-20 Weight distribution 
		if (randomInt > 0 && randomInt <= 6) {
			return LETTERS[Math.floor(Math.random() * LETTERS.length)];
		} else if (randomInt == 7 || randomInt == 8) {
			return NUMBERS[Math.floor(Math.random() * NUMBERS.length)];
		} else if (randomInt == 9 || randomInt == 10) {
			return SYMBOLS[Math.floor(Math.random() * SYMBOLS.length)];
		} else if (randomInt == 0) {
			return getRandomChar();
		}
	}

	function generatePassword(passwordLength) {
		let generatedPassword = '';

		for(let i = 0; i < passwordLength; i++) {
			generatedPassword += getRandomChar();
		}

		password = generatedPassword;
	}

	function copyToClipboard() {
		navigator.clipboard.writeText(password);
	}
	
	generatePassword(passwordLength);

</script>
<div class="flex h-screen">
	<div class="m-auto bg-[#497592] p-10 rounded-xl border-[2px] border-[#8BD4C6]">
		<p class="text-white pb-10 text-center text-3xl">Password Generator</p>
		<p class="text-white text-center text-xl">Characters: {passwordLength}</p>
		<center>
			<input class="w-[250px] p-2 mb-5" type=range bind:value={passwordLength} on:change={generatePassword(passwordLength)} min=8 max=20>
			<div class="">
				<input class="outline-none p-2 w-[320px] text-xl rounded-xl ring-2 ring-[#170F1E]/20" value={password} readonly>
				<button class="ml-[-40px] mt-[-5px] mr-[5px] align-middle drop-shadow" on:click={copyToClipboard}><CopyIcon/></button>
			</div>
			<button class="bg-[#3A566D] rounded p-2 mt-8 text-white text-lg font-medium" on:click={generatePassword(passwordLength)}>Generate Password</button>
		</center>
	</div>
</div>

// src/components/h4rasho/passwordGenerator.jsx
import { useState } from 'react'
import CopyIcon from './icons/copy'

const CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+'
const MIN_LENGTH = 8
const MAX_LENGTH = 16

export default function GeneratePassword() {
	const [pass, setPass] = useState('BADPASSWORD')
	const [length, setLength] = useState(MIN_LENGTH)
	const [showAlert, setShowAlert] = useState(false)

	const generatePassword = () => {
		let password = ''
		for (let i = 0; i < length; i++) {
			password += CHARACTERS.charAt(Math.floor(Math.random() * CHARACTERS.length))
		}
		setPass(password)
	}

	const handleCopy = () => {
		navigator.clipboard.writeText(pass)
		setShowAlert(true)
		setTimeout(() => {
			setShowAlert(false)
		}, 1000)
	}


	return (
		<>
			<div className='flex justify-center bg-slate-100 rounded-lg'>
				<p className='text-center p-5 text-3xl text-[#f4a261]' >{pass}</p>
				<button onClick={handleCopy}>
					<CopyIcon />
					{
						showAlert && (
							<div className='bg-[#e9c46a] text-[#264653] rounded-lg p-2 absolute'>
								<p className='text-center'>Password Copied!</p>
							</div>
						)
					}
				</button>
			</div>
			<input
				className='w-full rounded-lg bg-[#e9c46a] text-red-700 appearance-none cursor-pointer'
				type='range' min={MIN_LENGTH}
				max={MAX_LENGTH}
				value={length}
				onChange={e => setLength(e.target.value)}
				step={1}
			/>
			<button className='bg-[#e76f51] text-[#264653] w-full rounded-lg py-2 text-xl font-medium' onClick={generatePassword}>
				GENERATE
			</button>
			<p className='text-center text-[#f4a261] text-xl font-medium'>Password Length: {length}</p>
		</>
	)
}
