// src/components/samarjaffal/Password.svelte
<script>
export let password

let copied = false

function copyToClipboard({password}) {
		navigator.clipboard.writeText(password).then(() => {
				copied = true
				setTimeout(() => {
						copied = false
				}, 1000)
		});
	}

</script>
	
<div class={`p-6 rounded mt-5 flex justify-between items-center ${copied ? 'copied' : ''}`}>
	<p class="font-light text-2xl  bg-gradient-to-r from-amber-400 via-blue-400 to-purple-400 text-transparent bg-clip-text">{password}</p>
	<button type="button" id="copy-button" on:click={() => copyToClipboard({password})}>
		{#if copied}
			<svg width="48px" height="48px" stroke-width="1.72" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#000000"><path d="M1.5 12.5l4.076 4.076a.6.6 0 00.848 0L9 14M16 7l-4 4" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round"></path><path d="M7 12l4.576 4.576a.6.6 0 00.848 0L22 7" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round"></path>
			</svg>
		{:else}
			<svg width="48px" height="48px" stroke-width="1.72" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" color="#ffffff"><path d="M19.4 20H9.6a.6.6 0 01-.6-.6V9.6a.6.6 0 01.6-.6h9.8a.6.6 0 01.6.6v9.8a.6.6 0 01-.6.6z" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round" stroke-linejoin="round"></path><path d="M15 9V4.6a.6.6 0 00-.6-.6H4.6a.6.6 0 00-.6.6v9.8a.6.6 0 00.6.6H9" stroke="#ffffff" stroke-width="1.72" stroke-linecap="round" stroke-linejoin="round"></path>
			</svg>
		{/if}
	</button>
</div>

<style>
	div{
		background: #170F1EE6;
		background: linear-gradient(to right, #170F1EE6 50%, #64e2ff 50%);
		background-size: 200% 100%;
    background-position:left bottom;
		transition:all 0.8s ease;
	}
	.copied{
		background-position:right bottom;
	}
</style>

// src/components/EddCode/Password/index.jsx
import { useRef } from 'react'
import './styles.css'

const Password = ({ password }) => {
	const $password = useRef(null)

	const copyPassword = () => {
		navigator.clipboard.writeText($password.current.innerText)
		document.execCommand('copy')
	}

	return (
		<div className='flex justify-center mt-8'>
			<div className='password-box'>
				<span className='mr-5' ref={$password}>
					{password}
				</span>
				<button className='svg-container tooltip' onClick={copyPassword} disabled={!password} >
					<svg
						xmlns='http://www.w3.org/2000/svg'
						fill='none'
						viewBox='0 0 24 24'
						strokeWidth={1.5}
						stroke='currentColor'
						className='w-6 h-6 text-blue-400'
					>
						<path
							strokeLinecap='round'
							strokeLinejoin='round'
							d='M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z'
						/>
					</svg>
					<span className='tooltiptext'>Copied!</span>
				</button>
			</div>
		</div>
	)
}

export default Password
