// src/components/yesiddev/atoms/Checkbox.svelte
<script>
	export let label = ''
</script>

<div class="flex items-center pl-4 rounded-md border border-slate-400 my-2 hover:border-white duration-300">
	<input
		id={label}
		type="checkbox"
		value=""
		name="bordered-checkbox"
		class="w-4 h-4 appearance-none border rounded border-slate-400 checked:bg-blue-500 checked:border-transparent focus:outline-none"
	/>
	<label for={label} class="py-4 ml-2 w-full text-sm font-medium text-white cursor-pointer"
		>{label}</label
	>
</div>

// src/components/brayanbasallo/input/checkbox.vue
<template>
	<div class="flex items-start">
		<div class="flex items-center h-5">
			<input
				:id="id"
				type="checkbox"
				v-model="detail.active"
				value=""
				class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800"
			/>
		</div>
		<label :for="id" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-400">
			{{ detail.title }}
		</label>
	</div>
</template>

<script>
export default {
	name: 'checkbox',
	props: {
		detail: {
			required: true,
			type: Object
		},
		id: {
			required: true,
			type: String
		}
	}
}
</script>

<style scoped></style>
