// src/components/znareak/components/Footer/index.jsx
import React from 'react'
import css from './footer.module.css'

export default function Footer() {
	return (
		<footer className={css.footer}>
			<a href='https://www.twitch.tv/midudev' rel='noopener noreferrer' target='_blank'>
				midudev
			</a>
			<a href='https://libardo.vercel.app/' rel='noopener noreferrer' target='_blank'>
				znareak
			</a>
			<a href='https://hacktoberfest.com/' rel='noopener noreferrer' target='_blank'>
				hacktoberfest
			</a>
			<a
				href='https://github.com/midudev/password-generator'
				rel='noopener noreferrer'
				target='_blank'
			>
				github
			</a>
		</footer>
	)
}

// src/components/yeraldev/components/Footer.svelte
<section class="footer">
	<a
		class="external-link"
		href="https://hacktoberfest-2022.vercel.app"
		target="_blank"
		rel="noopener noreferrer"
	>
		midu-reto
	</a>
	<a
		class="external-link"
		href="http://hacktoberfest.com"
		target="_blank"
		rel="noopener noreferrer"
	>
		HACKTOBERFEST-2022
	</a>
</section>

<style>
	.footer {
		display: grid;
		gap: 1.5rem;
		padding-top: 2rem;
	}
	.external-link {
		color: var(--purple);
	}
	.external-link:hover {
		text-shadow: var(--text-shadow-hover);
		transform: scale(1.05);
	}
</style>
