// src/components/santimendoza/PasswordGenerator/index.jsx
import React from 'react'
import './PasswordGenerator.css'

function PasswordGenerator() {
	const [passwordLength, setPasswordLength] = React.useState(8)
	const [password, setPassword] = React.useState('')
	const [allowSpecialChars, setAllowSpecialChars] = React.useState(false)
	const [isCopied, setIsCopied] = React.useState(false)

	const generatePassword = () => {
		let newPassword = ''

		let availableChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvxyz1234567890'

		if (allowSpecialChars) {
			availableChars += '!"·$%&/()=?¿-.,;:_'
		}

		for (let i = 0; i < passwordLength; i++) {
			newPassword += availableChars[Math.floor(Math.random() * (availableChars.length))]
		}

		setPassword(newPassword)
	}

	const handleCopyPassword = () => {
		navigator.clipboard.writeText(password)
		setIsCopied(true)
		setTimeout(() => {
			setIsCopied(false)
		}, 500)
	}

	return (
		<div className='app-container'>
			<h1 className='app-container-title'>Password Generator</h1>
			<label htmlFor='password-length-slider'>Password Length: {passwordLength}</label>
			<input
				type='range'
				min='1'
				max='30'
				id='password-length-slider'
				value={passwordLength}
				onChange={(e) => setPasswordLength(e.target.value)}
			/>
			<label htmlFor='special-chars-check'>
				<input
					className='special-chars-checkbox'
					type='checkbox'
					checked={allowSpecialChars}
					onChange={() => setAllowSpecialChars(prevValue => !prevValue)}
				/>
				Allow Special Chars
			</label>
			<button className='generate-button' onClick={generatePassword}>Generate</button>
			{password &&
				<div className='password-generated'>
					<input className='password-input' type='text' disabled value={password} />
					<button className={`copy-button ${isCopied ? 'copied' : ''}`} onClick={handleCopyPassword}>📝 {isCopied ? 'Copied' : 'Copy'}</button>
				</div>
			}
		</div>
	)
}

export default PasswordGenerator

// src/components/kilombo/passwordGenerator.vue
<template>
	<div class="min-h-screen min-w-full flex text-white justify-center items-center">
		<section>
			<h1>Password Generator</h1>
			<p>Your password: <span id="generatedPasswordText" ref="generatedPasswordText"
					v-on:focus="$event.target.select()">{{generatedPassword}}</span><button v-if="generatedPassword"
					@click="copyToClipboard" class="mx-1">Copy</button></p>
			<input type="range" min="1" max="20" v-model="passwordLength" class="block" />
			<p class="">Length: {{passwordLength}} </p>
			<button @click="generatePassword" class="">Generate password</button>
		</section>
	</div>
</template>

<script>
export default {
	name: "passwordGenerator",
	components: {},
	data () {
		return {
			generatedPassword: '',
			passwordLength: 10,
			lowercaseChars: "abcdefghijklmnopqrstuvwxyz",
			uppercaseChars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
			numbersChars: "0123456789",
			symbolsChars: "!@#$%^&*_-+=",
			selectedChars: ''
		}
	},
	computed: {

	},
	methods: {
		generatePassword () {
			this.selectedChars = this.lowercaseChars;
			this.generatedPassword = this.generateString();
		},
		generateString () {
			let password = '';
			for (let i = 0; i < this.passwordLength; i++) {
				password += this.selectedChars.charAt(Math.floor(Math.random() * this.selectedChars.length)
				);
			}
			return password;
		},
		copyToClipboard () {
			navigator.clipboard.writeText(this.generatedPassword);
		}
	},
}
</script>
