// src/components/sergio-jc/components/InputRange.jsx
const InputRange = ({ value, change }) => {
	return (
		<div className='flex flex-col justify-center items-center gap-3'>
			<header className='flex gap-20 justify-around items-center'>
				<span className='text-purple-900 font-mono text-sm'>Character length</span>
				<span className='text-purple-900 font-mono font-bold text-lg w-6'>{value}</span>
			</header>
			<input
				type={'range'}
				className='h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 w-60'
				value={value}
				onChange={(e) => change(e.target.value)}
				min={0}
				max={20}
			/>
		</div>
	)
}

export default InputRange

// src/components/david-ponc/input-range.svelte
<script lang="ts">
	export let length: number
</script>

<fieldset class="flex flex-col gap-2 my-4">
	<div class="flex items-center justify-between gap-4">
		<label for="" class="text-zinc-400">Longitud</label>
		<span class="text-indigo-300 drop-shadow-md shadow-indigo-100 font-medium font-sans text-xl">
			{length}
		</span>
	</div>
	<input
		min="8"
		step="2"
		max="128"
		type="range"
		bind:value={length}
		class="appearance-none rounded-md bg-white/10 h-2 accent-zinc-300 active:accent-zinc-600 hover:accent-zinc-400"
	/>
</fieldset>
